"use client";

import { useCallback, useMemo, useState } from "react";
import EditEntryModal from "@/components/timesheets/EditEntryModal";
import TimesheetEmptyState from "@/components/timesheets/TimesheetEmptyState";
import TimesheetFilters, { type StatusFilter } from "@/components/timesheets/TimesheetFilters";
import TimesheetToolbar from "@/components/timesheets/TimesheetToolbar";
import WeeklyTimesheet from "@/components/timesheets/WeeklyTimesheet";
import WeekSummary from "@/components/timesheets/WeekSummary";
import type { Timesheet, TimesheetEntry, WeekRange, WeekSummary as WeekSummaryType } from "@/lib/types/timesheet";

type Props = { timesheet: Timesheet; employees: string[]; projects: string[]; weekRanges: WeekRange[] };
export default function TimesheetPage({ timesheet, employees, projects, weekRanges }: Props) { const [week, setWeek] = useState(timesheet.week.id); const [employee, setEmployee] = useState("all"); const [project, setProject] = useState("all"); const [status, setStatus] = useState<StatusFilter>("all"); const [search, setSearch] = useState(""); const [editingEntry, setEditingEntry] = useState<TimesheetEntry | null>(null); const [feedback, setFeedback] = useState(""); const closeModal = useCallback(() => setEditingEntry(null), []); const filteredEntries = useMemo(() => { const query = search.trim().toLowerCase(); if (week !== timesheet.week.id) return []; return timesheet.entries.filter((entry) => (employee === "all" || entry.employee === employee) && (project === "all" || entry.project === project) && (status === "all" || entry.status === status) && (!query || `${entry.employee} ${entry.project} ${entry.task} ${entry.notes}`.toLowerCase().includes(query))); }, [employee, project, search, status, timesheet, week]); const summary = useMemo<WeekSummaryType>(() => { const workedMinutes = filteredEntries.reduce((total, entry) => total + entry.workedMinutes, 0); const breakMinutes = filteredEntries.reduce((total, entry) => total + entry.breakMinutes, 0); const overtimeMinutes = filteredEntries.filter((entry) => entry.category === "overtime").reduce((total, entry) => total + Math.max(entry.workedMinutes - 480, 0), 0); return { workedMinutes, breakMinutes, overtimeMinutes, remainingMinutes: Math.max(2400 - workedMinutes, 0) }; }, [filteredEntries]); const hasFilters = week !== timesheet.week.id || employee !== "all" || project !== "all" || status !== "all" || search !== ""; const clear = () => { setWeek(timesheet.week.id); setEmployee("all"); setProject("all"); setStatus("all"); setSearch(""); }; const action = (label: "Submit" | "Approve" | "Reject") => { setFeedback(`${label} action recorded for preview only.`); /* TODO: Enforce company isolation, RLS and approval workflow through Supabase. */ }; const save = () => { setEditingEntry(null); setFeedback("Entry changes are ready for backend integration."); /* TODO: Persist validated changes through Supabase. */ }; return <div className="grid min-w-0 gap-5"><TimesheetFilters weeks={weekRanges} week={week} employee={employee} project={project} status={status} search={search} employees={employees} projects={projects} onWeek={setWeek} onEmployee={setEmployee} onProject={setProject} onStatus={setStatus} onSearch={setSearch} onClear={clear} hasFilters={hasFilters} /><WeekSummary summary={summary} /><TimesheetToolbar feedback={feedback} onAction={action} />{filteredEntries.length ? <WeeklyTimesheet entries={filteredEntries} onEdit={setEditingEntry} /> : <TimesheetEmptyState />}{editingEntry ? <EditEntryModal entry={editingEntry} projects={projects} onClose={closeModal} onSave={save} /> : null}</div>; }
