import type { EmployeeStatus } from "@/lib/types/employee";

export type StatusFilter = "all" | EmployeeStatus;
type Props = { search: string; status: StatusFilter; team: string; teams: string[]; onSearch: (value: string) => void; onStatus: (value: StatusFilter) => void; onTeam: (value: string) => void; onClear: () => void; hasFilters: boolean };

const control = "min-h-11 rounded-lg border border-white/10 bg-[#161A34] px-3 text-sm text-[#E5E7EB] outline-none focus:border-[#22C55E] focus:ring-2 focus:ring-[#22C55E]/20";
export default function EmployeeFilters(props: Props) {
  return <div className="grid gap-3 rounded-2xl border border-white/10 bg-[#161A34]/60 p-4 md:grid-cols-[minmax(12rem,1fr)_11rem_11rem_auto] md:items-end"><div><label htmlFor="employee-search" className="text-xs font-medium text-[#9CA3AF]">Search employees</label><input id="employee-search" type="search" value={props.search} onChange={(event) => props.onSearch(event.target.value)} placeholder="Name or email" className={`${control} mt-2 w-full`} /></div><div><label htmlFor="employee-status" className="text-xs font-medium text-[#9CA3AF]">Status</label><select id="employee-status" value={props.status} onChange={(event) => props.onStatus(event.target.value as StatusFilter)} className={`${control} mt-2 w-full`}><option value="all">All statuses</option><option value="active">Active</option><option value="invited">Invited</option><option value="inactive">Inactive</option></select></div><div><label htmlFor="employee-team" className="text-xs font-medium text-[#9CA3AF]">Team</label><select id="employee-team" value={props.team} onChange={(event) => props.onTeam(event.target.value)} className={`${control} mt-2 w-full`}><option value="all">All teams</option>{props.teams.map((team) => <option key={team} value={team}>{team}</option>)}</select></div><button type="button" onClick={props.onClear} disabled={!props.hasFilters} className="min-h-11 rounded-lg px-4 text-sm font-semibold text-[#9CA3AF] transition hover:bg-white/5 hover:text-[#E5E7EB] focus-visible:outline-2 focus-visible:outline-[#22C55E] disabled:cursor-not-allowed disabled:opacity-40">Clear filters</button></div>;
}
