"use client";

import type { FormEvent } from "react";
import Link from "next/link";

const field = "mt-2 min-h-12 w-full rounded-lg border border-white/10 bg-[#111827] px-4 text-base text-[#E5E7EB] outline-none placeholder:text-[#6B7280] focus:border-[#22C55E] focus:ring-2 focus:ring-[#22C55E]/20 user-invalid:border-red-400";
export default function EmployeeForm({ teams }: { teams: string[] }) {
  function preventSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); }
  return <form onSubmit={preventSubmit} className="rounded-2xl border border-white/10 bg-[#161A34] p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium text-[#E5E7EB]">First name<input name="firstName" autoComplete="given-name" required className={field} /></label><label className="text-sm font-medium text-[#E5E7EB]">Last name<input name="lastName" autoComplete="family-name" required className={field} /></label><label className="text-sm font-medium text-[#E5E7EB]">Work email<input name="email" type="email" autoComplete="email" required placeholder="name@company.com" className={field} /></label><label className="text-sm font-medium text-[#E5E7EB]">Phone<input name="phone" type="tel" autoComplete="tel" className={field} /></label><label className="text-sm font-medium text-[#E5E7EB]">Job title<input name="jobTitle" required className={field} /></label><label className="text-sm font-medium text-[#E5E7EB]">Team<select name="team" required defaultValue="" className={field}><option value="" disabled>Select team</option>{teams.map((team) => <option key={team} value={team}>{team}</option>)}</select></label><label className="text-sm font-medium text-[#E5E7EB]">Employment type<select name="employmentType" required defaultValue="employee" className={field}><option value="employee">Employee</option><option value="contractor">Contractor</option><option value="temporary">Temporary</option></select></label><label className="text-sm font-medium text-[#E5E7EB]">Hourly rate<input name="hourlyRate" type="number" min="0" step="0.01" inputMode="decimal" className={field} /></label><label className="text-sm font-medium text-[#E5E7EB] sm:col-span-2">Start date<input name="startDate" type="date" required className={field} /></label></div><p className="mt-6 rounded-lg bg-[#22C55E]/8 p-4 text-sm leading-6 text-[#9CA3AF]">The employee will receive an invitation when backend email delivery is integrated.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Link href="/dashboard/employees" className="flex min-h-11 items-center justify-center rounded-lg border border-white/15 px-5 text-sm font-semibold text-[#E5E7EB] hover:bg-white/5 focus-visible:outline-2 focus-visible:outline-[#22C55E]">Cancel</Link><button type="submit" className="min-h-11 rounded-lg bg-[#22C55E] px-5 text-sm font-semibold text-[#07110B] hover:bg-[#16A34A] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#22C55E]">Send invitation</button></div></form>;
}
