create extension if not exists pgcrypto;

create type public.membership_status as enum ('invited','active','suspended','ended');
create type public.relationship_type as enum ('client','contractor','subcontractor','partner');
create type public.project_status as enum ('planning','active','paused','completed','cancelled');
create type public.timesheet_status as enum ('draft','submitted','approved','rejected');
create type public.notification_type as enum ('INFO','WARNING','ACTION_REQUIRED','SUCCESS');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, name text not null, email text not null, avatar_url text, language text not null default 'en', timezone text not null default 'UTC', country text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.professional_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.users(id) on delete cascade, bio text, specialties text[] not null default '{}', languages text[] not null default '{}', social_links jsonb not null default '{}', portfolio jsonb not null default '[]', resume_url text, availability text);
create table public.companies (id uuid primary key default gen_random_uuid(), name text not null, vat text, website text, social_links jsonb not null default '{}', default_language text not null default 'en', currency text not null default 'EUR', timezone text not null default 'UTC', country text, city text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.roles (id uuid primary key default gen_random_uuid(), key text not null unique, name text not null, description text, system boolean not null default false);
create table public.permissions (id uuid primary key default gen_random_uuid(), key text not null unique, resource text not null, action text not null, scope text);
create table public.role_permissions (role_id uuid not null references public.roles(id) on delete cascade, permission_id uuid not null references public.permissions(id) on delete cascade, primary key (role_id, permission_id));
create table public.company_memberships (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, job_title text, function_name text, starts_at timestamptz not null default now(), ends_at timestamptz, status public.membership_status not null default 'invited', unique(company_id,user_id));
create table public.membership_roles (membership_id uuid not null references public.company_memberships(id) on delete cascade, role_id uuid not null references public.roles(id) on delete cascade, primary key(membership_id,role_id));
create table public.company_relationships (id uuid primary key default gen_random_uuid(), source_company_id uuid not null references public.companies(id), target_company_id uuid not null references public.companies(id), relationship_type public.relationship_type not null, status text not null default 'active', created_at timestamptz not null default now(), check(source_company_id <> target_company_id));
create table public.projects (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, client_company_id uuid references public.companies(id), name text not null, description text, status public.project_status not null default 'planning', manager_id uuid references public.users(id), starts_at date, ends_at date, estimated_hours numeric(10,2), cost_center text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.chantiers (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, project_id uuid references public.projects(id) on delete set null, client_company_id uuid references public.companies(id), name text not null, address jsonb not null default '{}', latitude numeric(9,6), longitude numeric(9,6), po_number text, cost_center text, manager_id uuid references public.users(id), starts_at date, ends_at date, status text not null default 'planned');
create table public.timesheets (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, user_id uuid not null references public.users(id), period_start date not null, period_end date not null, status public.timesheet_status not null default 'draft', submitted_at timestamptz, reviewed_by uuid references public.users(id), reviewed_at timestamptz, unique(company_id,user_id,period_start,period_end));
create table public.timesheet_entries (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, timesheet_id uuid not null references public.timesheets(id) on delete cascade, project_id uuid references public.projects(id), chantier_id uuid references public.chantiers(id), starts_at timestamptz not null, ends_at timestamptz not null, break_minutes integer not null default 0, notes text, check(ends_at > starts_at), check(break_minutes >= 0));
create table public.reports (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade, requested_by uuid not null references public.users(id), type text not null, format text not null, status text not null default 'queued', parameters jsonb not null default '{}', file_url text, requested_at timestamptz not null default now(), completed_at timestamptz);
create table public.notifications (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, type public.notification_type not null, title text not null, message text not null, action_url text, read_at timestamptz, created_at timestamptz not null default now());
create table public.certificates (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, issuer text not null, issued_at date not null, expires_at date, credential_id text, document_url text);
create table public.audit_logs (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete set null, actor_id uuid references public.users(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', occurred_at timestamptz not null default now());
create table public.localization_settings (id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete cascade, user_id uuid references public.users(id) on delete cascade, language text not null, timezone text not null, locale text not null, date_format text not null, currency text not null, check(company_id is not null or user_id is not null));
create table public.user_settings (user_id uuid primary key references public.users(id) on delete cascade, theme text not null default 'system', default_company_id uuid references public.companies(id), notification_preferences jsonb not null default '{}', compact_mode boolean not null default false);
create table public.company_settings (company_id uuid primary key references public.companies(id) on delete cascade, approval_required boolean not null default true, week_starts_on smallint not null default 1, notifications_enabled boolean not null default true, accounting_provider text);

create index on public.company_memberships(user_id, company_id) where status = 'active';
create index on public.projects(company_id); create index on public.chantiers(company_id); create index on public.timesheets(company_id,user_id); create index on public.timesheet_entries(company_id); create index on public.reports(company_id); create index on public.notifications(user_id,company_id); create index on public.audit_logs(company_id,occurred_at desc);

create schema if not exists private;
create or replace function private.is_company_member(target_company_id uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists(select 1 from public.company_memberships m where m.company_id = target_company_id and m.user_id = (select auth.uid()) and m.status = 'active') $$;
revoke all on function private.is_company_member(uuid) from public; grant execute on function private.is_company_member(uuid) to authenticated;

do $$ declare table_name text; begin foreach table_name in array array['users','professional_profiles','companies','roles','permissions','role_permissions','company_memberships','membership_roles','company_relationships','projects','chantiers','timesheets','timesheet_entries','reports','notifications','certificates','audit_logs','localization_settings','user_settings','company_settings'] loop execute format('alter table public.%I enable row level security', table_name); end loop; end $$;

create policy "users_read_self" on public.users for select to authenticated using ((select auth.uid()) = id);
create policy "memberships_read_own" on public.company_memberships for select to authenticated using (user_id = (select auth.uid()));
create policy "companies_read_member" on public.companies for select to authenticated using ((select private.is_company_member(id)));
do $$ declare table_name text; begin foreach table_name in array array['projects','chantiers','timesheets','timesheet_entries','reports','audit_logs','company_settings'] loop execute format('create policy %I on public.%I for select to authenticated using ((select private.is_company_member(company_id)))', table_name || '_tenant_read', table_name); execute format('create policy %I on public.%I for insert to authenticated with check ((select private.is_company_member(company_id)))', table_name || '_tenant_insert', table_name); execute format('create policy %I on public.%I for update to authenticated using ((select private.is_company_member(company_id))) with check ((select private.is_company_member(company_id)))', table_name || '_tenant_update', table_name); end loop; end $$;
create policy "notifications_read_own" on public.notifications for select to authenticated using (user_id = (select auth.uid()) and (company_id is null or (select private.is_company_member(company_id))));

insert into storage.buckets (id,name,public) values ('avatars','avatars',false),('company-logos','company-logos',false),('documents','documents',false),('reports','reports',false),('certificates','certificates',false),('project-images','project-images',false),('site-photos','site-photos',false) on conflict(id) do nothing;
create policy "storage_authenticated_read" on storage.objects for select to authenticated using (bucket_id in ('avatars','company-logos','documents','reports','certificates','project-images','site-photos'));
