"use client";

import { useTranslations } from "next-intl";
import type { Client, ProjectPriority, ProjectStatus } from "@/lib/types/project";
export type ProjectFiltersValue = { search: string; client: string; status: "all" | ProjectStatus; priority: "all" | ProjectPriority };
const control = "min-h-11 w-full rounded-lg border border-white/10 bg-[#111827] px-3 text-sm text-[#E5E7EB] outline-none focus:border-[#22C55E] focus:ring-2 focus:ring-[#22C55E]/20";
const statusKeys: Record<ProjectStatus, string> = { planning: "statusPlanning", active: "statusActive", paused: "statusPaused", completed: "statusCompleted", cancelled: "statusCancelled" };
const priorityKeys: Record<ProjectPriority, string> = { low: "priorityLow", medium: "priorityMedium", high: "priorityHigh", critical: "priorityCritical" };
export default function ProjectFilters({ value, clients, onChange, onClear, hasFilters }: { value: ProjectFiltersValue; clients: Client[]; onChange: (value: ProjectFiltersValue) => void; onClear: () => void; hasFilters: boolean }) {
  const t = useTranslations("projects");
  return <div className="grid gap-3 rounded-2xl border border-white/10 bg-[#161A34] p-4 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_1fr_auto]"><div><label htmlFor="project-search" className="sr-only">{t("searchProjects")}</label><input id="project-search" type="search" value={value.search} onChange={(event) => onChange({ ...value, search: event.target.value })} placeholder={t("searchPlaceholder")} className={control}/></div><div><label htmlFor="client-filter" className="sr-only">{t("srFilterClient")}</label><select id="client-filter" value={value.client} onChange={(event) => onChange({ ...value, client: event.target.value })} className={control}><option value="all">{t("allClients")}</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.companyName}</option>)}</select></div><div><label htmlFor="status-filter" className="sr-only">{t("srFilterStatus")}</label><select id="status-filter" value={value.status} onChange={(event) => onChange({ ...value, status: event.target.value as ProjectFiltersValue["status"] })} className={control}><option value="all">{t("allStatuses")}</option>{(Object.keys(statusKeys) as ProjectStatus[]).map((status) => <option key={status} value={status}>{t(statusKeys[status])}</option>)}</select></div><div><label htmlFor="priority-filter" className="sr-only">{t("srFilterPriority")}</label><select id="priority-filter" value={value.priority} onChange={(event) => onChange({ ...value, priority: event.target.value as ProjectFiltersValue["priority"] })} className={control}><option value="all">{t("allPriorities")}</option>{(Object.keys(priorityKeys) as ProjectPriority[]).map((priority) => <option key={priority} value={priority}>{t(priorityKeys[priority])}</option>)}</select></div><button type="button" onClick={onClear} disabled={!hasFilters} className="min-h-11 rounded-lg border border-white/15 px-4 text-sm font-semibold text-[#E5E7EB] disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-2 focus-visible:outline-[#22C55E]">{t("clear")}</button></div>;
}
