"use client";

import { useTranslations } from "next-intl";
import type { Client, Project } from "@/lib/types/project";
import ClientCard from "./ClientCard"; import ProjectStats from "./ProjectStats"; import ProjectStatusBadge from "./ProjectStatusBadge";
export default function ProjectSummary({ project, client }: { project: Project; client: Client }) {
  const t = useTranslations("projects");
  const progress = Math.min(100, Math.round(project.workedHours / project.estimatedHours * 100));
  const priorityKey = `priority${project.priority.charAt(0).toUpperCase()}${project.priority.slice(1)}`;
  return <div className="grid gap-5"><ProjectStats project={project} /><div className="grid gap-5 lg:grid-cols-[1fr_20rem]"><article className="rounded-2xl border border-white/10 bg-[#161A34] p-5 sm:p-7"><div className="flex flex-wrap gap-2"><ProjectStatusBadge status={project.status}/><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs font-semibold capitalize text-[#D1D5DB]">{t("priorityLabel", { priority: t(priorityKey) })}</span></div><h3 className="mt-6 font-semibold text-[#E5E7EB]">{t("progress")}</h3><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10" role="progressbar" aria-label={t("projectHoursProgress")} aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-[#22C55E]" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-sm text-[#9CA3AF]">{t("hoursOf", { worked: project.workedHours, estimated: project.estimatedHours, progress })}</p><h3 className="mt-7 font-semibold text-[#E5E7EB]">{t("description")}</h3><p className="mt-2 text-sm leading-6 text-[#9CA3AF]">{project.description}</p><h3 className="mt-7 font-semibold text-[#E5E7EB]">{t("teamMembers")}</h3><ul className="mt-3 grid gap-3 sm:grid-cols-2">{project.members.map((member) => <li key={member.id} className="flex items-center gap-3 rounded-xl bg-[#111827]/70 p-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#22C55E]/10 text-xs font-bold text-[#22C55E]">{member.initials}</span><span><span className="block text-sm font-semibold text-[#E5E7EB]">{member.name}</span><span className="text-xs text-[#9CA3AF]">{member.role}</span></span></li>)}</ul></article><ClientCard client={client}/></div></div>;
}
